Interface support
yahoo/proxy-verifier pull request #147
Opened 2021-04-14 15:07 UTC by willwendorfvm

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Supports an options that sends a bound-to device for all client sockets on verifier-client.

2021-04-14 16:23 UTC, bneradt requested changes
Looks good Will. I just have a few small tweaks.

2021-04-14 16:23 UTC, bneradt commented on local/src/core/http.cc
> +    if (device.length() && setsockopt(socket_fd, SOL_SOCKET, SO_BINDTODEVICE, device.data(), device.length())) {
A couple small things:

* Let's use `!device.empty()`. That more explicitly expresses the desired semantic.
* Please compare setsockopt with `< 0` for the error check.

Related to both of these, my general convention in conditions is to explicitly compare against a value in all but boolean function returns or variables.  Thus this is fine:

`if (!device.empty())`

That returns a boolean so a direct condition against that is fine.

However, for all conditions that are not boolean, explicitly compare. Thus this:

`if (ptr != nullptr)`

Not this:

`if (ptr)`

And this:

`if (retval > 0)`

Not this:

`if (retval)`

Let me know if I'm not explaining this well. In doing these explicit comparisons, I'm implementing what is recommended in "Code Complete" chapter 19.1, "Boolean Expressions".

2021-04-14 16:23 UTC, bneradt commented on local/src/client/verifier-client.cc
> +          "Specify a network device for the client to connect on.",
"Specify the network device from which the client will establish connections."

2021-04-16 19:35 UTC, bneradt requested changes

2021-04-16 19:35 UTC, bneradt commented on local/src/core/http.cc
> +    }
I suppose this should break here.

Thinking through this further, this functionality would be better encapsulated in a class which can enforce RAII on the allocated struct ifaddrs from getifaddrs.

What do you think of this:
https://github.com/bneradt/proxy-verifier/tree/interface_review2

2021-04-16 20:17 UTC, bneradt requested changes
Looks good. Can you run format.sh on this though? I hadn't run that on my branch.

2021-04-16 20:17 UTC, bneradt commented on local/src/core/http.cc
> +  auto const &family = ip.family();
family() is just an int. Better to copy and drop `&`.

2021-04-16 21:18 UTC, bneradt requested changes

2021-04-16 21:18 UTC, bneradt commented on local/src/core/http.cc
> +}
I talked to Alan. This whole function can be removed with the caller having:

```
std::string ip_string;
swoc::bwprint(ip_string, "{}", ip_endpoint);
```

Very nice.

2021-04-16 21:32 UTC, bneradt approved these changes

2021-04-19 16:32 UTC, bneradt requested changes

2021-04-19 16:32 UTC, bneradt commented on local/src/core/http.cc
> +      ip_string);
Oh wait, maybe we don't need ip_string at all. @willwendorfvm : can you try just passing int ip_endpoint for this argument?

2021-04-19 17:58 UTC, SolidWallOfCode approved these changes

2021-04-19 19:52 UTC, bneradt requested changes

2021-04-19 19:52 UTC, bneradt commented on README.md
> +Initiate connections from the specified interface. You can enter any name supported by setsockopt BINDTODEVICE, such at eth0:1.
Oh, let's not mention the socket option BINDTODEVICE now that we just manually bind. Maybe simplify it to just:

`Initiate connections from the specified interface, such as eth0:1.`

2021-04-19 20:01 UTC, bneradt approved these changes

2021-04-19 20:01 UTC, merged