Add support for GOAWAY frame
yahoo/proxy-verifier pull request #238
Opened 2023-01-09 19:58 UTC by duke8253

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Add support for GOAWAY frame, also adjusted the RST_STREAM frame autests.

2023-01-10 23:38 UTC, bneradt requested changes
Looks great to me. Just some minor observations. Thanks for working on this.

2023-01-10 23:38 UTC, bneradt commented on Sconstruct
> +                        tag="v1.51.0"
Thanks for helping keep these updated.

2023-01-10 23:38 UTC, bneradt commented on local/src/core/http2.cc
> +      if (submit_status) {
Nit: can you make this `submit_status != 0`. Only with boolean vars do we not compare to some value.

2023-01-10 23:38 UTC, bneradt commented on local/src/core/http2.cc
> +    errata.note(S_DIAG, "Received RST_STREAM frame with stream id {}", frame->hd.stream_id);
While you're at it, can you also add the error code to this? That could be helpful under some circumstances.

2023-01-10 23:38 UTC, bneradt commented on local/src/core/http2.cc
> +        frame->goaway.last_stream_id);
Error code here too please.

2023-01-10 23:38 UTC, bneradt commented on test/autests/gold_tests/http2_abort/replay_files/client_goaway_after_headers.yaml
> +meta:
We should add the Apache license for replay files. I think I've missed that in other replay files... we should add that with a separate commit. Don't worry for this PR. But for this new file, let's add the license.

2023-01-11 16:29 UTC, duke8253 commented on README.md
> +a stream, `GOAWAY` frame terminates the connection. It also uses the same set of `error-code` listed
But the RFC doc says this 

> The GOAWAY frame (type=0x7) is used to initiate shutdown of a connection or to signal serious error conditions.

2023-01-11 19:23 UTC, bneradt commented on README.md
> +a stream, `GOAWAY` frame terminates the connection. It also uses the same set of `error-code` listed
Good point. Let's stick with the paragraph as you wrote it. Thanks for pointing this out.

2023-01-11 19:27 UTC, bneradt approved these changes
Looks good. Thanks for the quick turn around on reviews.

2023-01-11 19:27 UTC, merged